### ISSUE TITLE
Using TagUI in nodered

### ISSUE THREAD

**Issue by marcelocecin** [open-rpa/examples-files#3]
hello x, how are you?
Is it possible to run the example image_search.json with a free openflow account?
in my case, the TagUI step is stuck with Spawn status
thanks

<img width="1339" alt="" src="https://user-images.githubusercontent.com/2955762/202876423-e7827172-051e-49c5-a091-18e747b9ebfd.png">
<img width="1437" alt="" src="https://user-images.githubusercontent.com/2955762/202876425-3f067eb8-18d8-4a2e-9bf9-3a413674d3c3.png">

**Comment by skadefro** [comment]
When me and ken, initially set this up and made a few post and videos about it, I had to increase memory in my free tie from 150 to 225 so people could try it out ... i guess that is not enough any more ( that is chrome, not tagui's fault ) 
I have increased it a bit more, but I might decrease it again later ... RAM is quite expensive, especially for a small company that is not making a profit. If you intent on really using this, you should install openflow locally or buy a NodeRED instance with more ram ( https://github.com/open-rpa/docker )

<blockquote><img src="https://opengraph.githubassets.com/4d8090c7a535acb3b4e0a06de8f182af9f3c75c674f26bc8f6d64f2727893f30/open-rpa/docker" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/open-rpa/docker">GitHub - open-rpa/docker</a></strong></div><div>Contribute to open-rpa/docker development by creating an account on GitHub.</div></blockquote>

**Comment by marcelocecin** [comment]
thank you very much Allan, I tried to create a new NodeRed but it still has 225 of memory

**Comment by skadefro** [comment]
The cache takes a while to update, you can try again.
If you still have issues or question, can we then please move this dialog to the correct forum. This is not an issue with the examples. but about my services, so please use the [community ](https://community.openiap.io/) for that.

**Comment by skadefro** [comment]
I turned it up to 256 and it works sometimes, but more often than not, kubernetes kill the pod due to RAM going beyond that.
If i start one with 512MB it both spawns and run fast, reliable every time.
![image](https://user-images.githubusercontent.com/4155937/202905116-85dfc2e4-71bf-458d-ace5-495109373e9e.png)

I suggest you test this locally instead, if you need a free option. I cannot increase the RAM any more, since i'm paying this out of my own pockets.
